name: Create release
on:
  push:
    - master
    - 82-interactive-cli
jobs:
  create-release:
    name: Build and create a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build application
        run: |
          wget https://go.dev/dl/go1.18.3.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.18.3.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          go version
          go build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "${{ github.ref }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            drupal9ci
