name: Create release
on:
  push:

jobs:
  create-release:
    name: Build and create a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build application
        run: |
          wget https://go.dev/dl/go1.18.3.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.18.3.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          go version
          go build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "drupal9ci"
          commit: "${{ github.ref_name }}"
          tag: "${{ github.ref_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}
