name: Create release
on:
  push:
    branches:
      - master
      - 82-interactive-cli
jobs:
  create-release:
    name: Build and create a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: Build application
        run: |
          go build
      - name: Set short sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: ${{ steps.vars.outputs.sha_short }}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            drupal9ci
