name: Merge actions
on:
  push:

jobs:
  release-linux-amd64:
    name: Build and create a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build application
        run: |
          wget https://go.dev/dl/go1.18.3.linux-amd64.tar.gz
          rm -rf /usr/local/go && tar -C /usr/local -xzf go1.18.3.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          go version
          go build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: latest
          title: "${{ GITHUB_SHA }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            drupal9ci
