name: Merge actions
on:
  push:
#    branches:
#      - master
#      - 82-interactive-cli
jobs:
  release-linux-amd64:
    name: Build and create a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.29
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          release_tag: ${{ GITHUB_SHA }}

  publish-docker-image:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: drupal9ci
          tags: latest
          registry: ghcr.io
          githubOrg: lullabot
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
