name: Test
on:
  push:

jobs:
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: Build application
        run: |
          go build
      - name: Build Drupal skeleton with Composer Drupal Project
        run: |
          composer create-project drupal-composer/drupal-project:9.x-dev drupal --stability dev --no-interaction
      - name: Copy application binary and run it
        run: |
          cp drupal9ci drupal
          cd drupal
          # We can't test interactive mode here so we pass a CI provider.
          ./drupal9ci Bitbucket

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: Run tests with coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out
          fail_ci_if_error: true
          verbose: true
